// Reference : https://www.youtube.com/watch?v=mHU4iqcRaQ8

strategy("Best Pullback Trading Strategy", overlay=true, initial_capital = 1000, default_qty_type=strategy.percent_of_equity, default_qty_value=100, pyramiding=0)

ma_length1 = input(200, "MA Length", step = 10, group="Moving Average Parameters", inline = "MA")
ma_length2 = input(13, "MA Length 2", step = 10, group="Moving Average Parameters", inline = "MA")
sl = input.float(title="Stop Loss", defval=0.07, step=0.1, group="Moving Average Parameters")
too_deep = input(title="Too Deep (%)", type=input.float, defval=0.27, step=0.01, group="Too eep and Thin conditions", inline="Too Deep")
too_thin = input(title="Too Thin (%)", type=input.float, defval=0.03, step=0.01, group="Too eep and Thin conditions", inline="Too Thin")

ma1 = ta.sma(close, ma_length1)
ma2 = ta.sma(close, ma_length2)
too_deep2 = (ma2/ma1-1) < too_deep
too_thin2 = (ma2/ma1-1) > too_thin

var float buy_price = na
buy_condition = (close > ma1) and (close < ma2) and strategy.position_size == 0 and too_deep2 and too_thin2
close_condition1 = (close > ma2) and security.position_size > 0 and (close < low[1])
stop_distance = strategy.position_size > 0 ? ((buy_price - close) / close : na
close_condition1 = strategy.position_size > 0 and stop_distance > sl
stop_price = strategy.position_size > 0 ? buy_price - (buy_price * sl) : na

if buy_condition
    strategy.entry("Buy", strategy.long)

if buy_condition[1]
    buy_price := open
if close_condition1 or close_condition2
    strategy.close("Buy", comment="Stop Loss" + (close_condition2) )
    buy_price := na

plot(ma1)
plot(ma2)
